### ISSUE TITLE
In firefox, PowerGlitch produces hundreds of console warnings when animation is playing.

### ISSUE THREAD

**Issue by KorayAydemir** [7PH/react-powerglitch#2]
Related (and fixed) issue on original repo: https://github.com/7PH/powerglitch/issues/17

https://user-images.githubusercontent.com/54016693/236705719-ce119578-c5ab-4314-85e4-491ac8dd5eb4.mp4

**Comment by 7PH** [comment]
Hey there 👋 released in [`v1.0.1`](https://github.com/7PH/react-powerglitch/releases/tag/v1.0.1)
