### ISSUE TITLE
Error `Property 'status' does not exist on type 'ComponentClass<ReactSoundProps, any>'.` when using Typescript

### ISSUE THREAD

**Issue by gabrielduete** [7PH/react-powerglitch#4]
Hi! All good?

I'm having these errors when using TypeScript, do we know how I can solve it?

Error: `Property 'status' does not exist on type 'ComponentClass<ReactSoundProps, any>'.`

![image](https://github.com/7PH/react-powerglitch/assets/59345698/50310904-a4a0-4537-9dfb-e5de5553f888)
--
Solution when using tyepscript;
![image](https://github.com/7PH/react-powerglitch/assets/59345698/82906675-e9b4-45a6-b015-0c81a79d9afe)

**Comment by 7PH** [comment]
Hello @gabrielduete , as far as I know, your issue has nothing to do with this library. Please provide more details if you think this is incorrect. I am closing this issue.
