### ISSUE TITLE
No type declarations in NPM package

### ISSUE THREAD

**Issue by SY573M404** [7PH/react-powerglitch#5]
There's no type declarations in v1.0.1 package published a week ago. There was `types/` directory in v1.0.0, and there isn't in v1.0.1. Therefore, I am unable to use it in TypeScript project

**Comment by 7PH** [comment]
That's correct, thank you for notifying me, I'm pushing a fix now

**Comment by 7PH** [comment]
Hey @SY573M404 , that's deployed to npm, you can install v1.0.2 which has the types declarations. Thanks again 👍
